# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428baeca5381a7a781febc05730d5123f92414bcf4d59af9ca1014550654268924ed17a951279823b6000d3ce28ac5b403d4e349ad64f039a2002c8127aeeb59

test:
  secret_key_base: 0e3c2a6a1fbe2d2118a9edb762e90dc4a021d34b04cfbe17f3d346f728c8fb7f6ea3100f1e48d14c7eb9f5949083713b6d70ae0374c45715579fba7d695262ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
